name: Trigger auto deployment for my-spring-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/my-spring-app-AutoDeployTrigger-68f2557e-3f00-4c6b-83c9-57abce0200a8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MYSPRINGAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYSPRINGAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYSPRINGAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.MYSPRINGAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYSPRINGAPP_REGISTRY_PASSWORD }}
          containerAppName: my-spring-app
          resourceGroup: class
          imageToBuild: ghcr.io/my-spring-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


